### PR TITLE
duplicate-cluster: Don't double count reconnection attempts

### PR DESCRIPTION
**Pull request by kklin**
Before, we simply counted the number of lines containing the string
"Registering worker" to determine the number of Spark workers
connecting to a master. However, sometimes when a worker attempts to
reconnect, it produces repeated lines in the log. We now parse the
master logs, and only count unique worker IP addresses.

### CODE REVIEW

**Comment by kklin** [comment]
I'm not sure @kayousterhout, you can see 10.169.159.254 reconnects here:
Worker container: http://jenkins.quilt.io:8080/job/quilt-tester/189/artifact/61-duplicate-cluster_debug_logs/containers/a672f20b3dfbdc04f41244b22b75f8222a50500f/logs/*view*/
Test output (with master logs): http://jenkins.quilt.io:8080/job/quilt-tester/189/testReport/junit/(root)/tests/61_duplicate_cluster/

Do you have any ideas? Do you think it might be a sign of something broken with Quilt?

**Comment by kayousterhout** [comment]
It's a little weird but based on the log messages I can't see anything
obviously wrong.  It's possible the first messages are somehow being
received before the master has been completely initialized, so it doesn't
process them correctly (which would mean it's not a Quilt error).

**Comment by kklin** [comment]
BTW, it only happens on DigitalOcean I think. Might be a timing issue due to different instance sizes?

**Comment by kayousterhout** [comment]
Does it happen consistently on digital ocean?

**Comment by kklin** [comment]
It's hard to tell from a glance at Jenkins, but I'd say about 1/5 of the time it runs on DigitalOcean this test fails, and I don't remember seeing it fail on any of the other providers.

**Pull request merged**
